name: floating_bar
description: "A Draggable Floating Bar.When tapped, the children expand to be visible, draggable via drag, and upon onPanEnd, designed to reattach to the left or right based on the given screen center."
version: 0.0.3
repository: https://github.com/Sun-Kwak/floating_bar.git

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
