name: floating_bar
description: "A Floating Bar."
version: 0.0.2
repository: https://github.com/Sun-Kwak/floating_bar.git

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
